Website update
prshreshtha/cblib.site pull request #5
Opened 2019-10-15 16:54 UTC by gustavtrolle

- Updated information and links
- New page for bookings
- Don't worry about the JavaScript stuff, it's all commented out

2019-10-16 09:19 UTC, prshreshtha commented
Hi there @gustavtrolle! Thank you for the contribution. I'm glad that this website is still going!

It appears that your PR includes already built files.

Notice [public/assets/](https://github.com/gustavtrolle/cblib.site/tree/22f61ada2ea439e766bf350aad8dce1bad5a256e/public/assets) (minified) and [public/](https://github.com/gustavtrolle/cblib.site/tree/22f61ada2ea439e766bf350aad8dce1bad5a256e/public/) (unminified) are both included.

Only the unminified code should be checked in to Git. I'm unsure how those files got there for you. Following the [README.md](https://github.com/prshreshtha/cblib.site/blob/f897e37b7e94a0ecff9e3ec8e37ccd85e3dfbea8/README.md), all those should have ended up in `deploy/`.

Could you clean up the files? You claim that your changes include:
> * Updated information and links
> * New page for bookings

This should only touch a few files, not 171.

Cheers,
Pranjal

2019-10-16 09:23 UTC, prshreshtha commented
As an aside, I can add you as a collaborator if you will be making changes to the website from here on. I see your changes are already live at http://colonelby.com/teachers/library/

2019-10-16 16:32 UTC, gustavtrolle commented
Sorry about that! I was transferring the website files to my new laptop and I guess something must've gone wrong. I have removed the additional files.

Also, another student will be in charge of the website, but I don't have his GitHub account at the moment. You can add him as a collaborator later.

Thanks,
Patrick

2019-10-18 03:28 UTC, praihan requested changes
If you're adding more konami codes, please let me know what they are!

2019-10-18 03:28 UTC, prshreshtha commented on public/assets/js/vendor/k.js
> +        /*codeD: function (link) {
Can you explain what these are? There's no reason to leave commented out code if it's in Git. You can always recover them from the commit history if needed.

2019-10-18 03:28 UTC, prshreshtha commented
I see that many of the files changed modes from `10644` to `10755`. This is from adding executable permission bits but these files should not be executable. Can you set them back?

2019-10-18 03:34 UTC, prshreshtha commented
> Also, another student will be in charge of the website, but I don't have his GitHub account at the moment. You can add him as a collaborator later.

Sure thing. Point him to me if you get the chance.

2022-07-23 22:59 UTC, closed without merging